options:
  logging: 'NONE' # 不需要日誌
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/iti-poc-372910/simple-node-app-gar/simple-node-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/iti-poc-372910/simple-node-app-gar/simple-node-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'simple-node-service', '--image', 'asia-east1-docker.pkg.dev/iti-poc-372910/simple-node-app-gar/simple-node-app', '--region', 'asia-east1', '--allow-unauthenticated', '--platform', 'managed']

images:
  - 'asia-east1-docker.pkg.dev/iti-poc-372910/simple-node-app-gar/simple-node-app'
